Ensure Content-Length is set for Responses that need it
ponylang/http_server pull request #74
Opened 2024-02-10 23:14 UTC by mfelsche

For all ways to construct responses, ensure that they have a `Content-Length` header, adding one with `0` as value if none was provided.
Do not add one for responses with `Transfer-Encoding: chunked`.

Obsoletes #71

2024-02-10 23:37 UTC, ponylang-main commented
<!-- release-note-reminder-bot -->
Hi @mfelsche,

The changelog - fixed label was added to this pull request; all PRs with a changelog label need to have release notes included as part of the PR. If you haven't added release notes already, please do.

Release notes are added by creating a uniquely named file in the `.release-notes` directory. We suggest you call the file `74.md` to match the number of this pull request.

The basic format of the release notes (using markdown) should be:

```
## Title

End user description of changes, why it's important,
problems it solves etc.

If a breaking change, make sure to include 1 or more
examples what code would look like prior to this change
and how to update it to work after this change.
```

Thanks.

2024-02-10 23:40 UTC, SeanTAllen commented
@mfelsche I think this should get 2 changelog entries. And two release notes. As this is pretty much two changes. 

1. the fix for including content-length for one shot.
2. the stuff that is "a breaking change"

can you manually add the slightly different and appropriate CHANGELOG entries. 1 to changed and 1 to fixed?

and manually add to next-release.md. different entries with names that match those in the changelog. the fixed should be simple, for the changed, detail what has changed about the API and what needs to be updated to adjust?

also you need to rebase it appears.

2024-02-10 23:40 UTC, SeanTAllen requested changes
I left a comment with "changes". Basically, the changelog entries and release notes entries.

2024-02-13 18:41 UTC, SeanTAllen commented on CHANGELOG.md
> +- Responses without `Transfer-Encoding: chunked` had no `Content-Length` header set when not done explicitly. This made some clients (e.g. curl) hang.
This isn't a changelog entry. It's very long. This should be a short title and link to the PR

Same for all the others.

2024-02-13 18:43 UTC, SeanTAllen commented on .release-notes/next-release.md
> +- `BuildableResponse.set_transfer_coding()` changed to `BuildableResponse.set_transfer_encoding()`
Can you make these individual entries as appropriate with "before and after" code examples?

The name for each `##` entry should match up with an entry in the CHANGELOG.

2024-02-13 18:45 UTC, SeanTAllen commented on CHANGELOG.md
> +- Responses without `Transfer-Encoding: chunked` had no `Content-Length` header set when not done explicitly. This made some clients (e.g. curl) hang.
our standard is along the lines of this one I pulled as an example from the file:

```
- Update to ponylang/net_ssl 1.3.2 ([PR #69](https://github.com/ponylang/http_server/pull/69))
```

2024-02-13 18:46 UTC, SeanTAllen commented on CHANGELOG.md
> +  - `Response.transfer_coding()` changed to `.transfer_encoding()`.
I'm not sure why the changelog tool is accepting these as valid. I'll have to look into it.

2024-02-18 19:07 UTC, merged